server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: flight-service
logging:
  level:
    root: INFO
    com.aiorchestration: DEBUG
    org.springframework.ai: INFO

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
